deployment.security.level=ALLOW_UNSIGNED
deployment.security.mixcode=DISABLE
deployment.security.expired.warning=false
deployment.security.jsse.hostmismatch.warning=false
deployment.security.sandbox.awtwarningwindow=false

